# Generated by Django 5.2.3 on 2025-08-10 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=10, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('card_token', models.CharField(max_length=255, verbose_name='Card Token')),
                ('cardholder_name', models.CharField(max_length=255, verbose_name='Cardholder Name')),
                ('last_four_digits', models.CharField(max_length=4, verbose_name='Last Four Digits')),
                ('brand', models.CharField(max_length=255, verbose_name='Brand')),
                ('expire_month', models.CharField(max_length=2, verbose_name='Expire Month')),
                ('expire_year', models.CharField(max_length=4, verbose_name='Expire Year')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Is confirmed')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.providers', verbose_name='Provider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cards', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Card',
                'verbose_name_plural': 'User Cards',
            },
        ),
    ]
